### ISSUE TITLE
Store new example fed.env file in to-be-created config file repository

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#82] opened 2023-11-27 18:56 UTC
As discussed in https://github.com/neurobagel/api/issues/162 we need to store a copy of the new federation-API docker-compose file in the yet-to-be-created "recipe" repo so user can easily download and use it.

_Originally posted by @surchs in https://github.com/neurobagel/documentation/pull/133#discussion_r1402782925_

**Comment by alyssadai** [comment] 2023-11-28 04:09
Duplicate of https://github.com/neurobagel/planning/issues/80, I think

**Closed** 2023-12-05 17:45 UTC
